import React, { Component } from "react";
import "assets/css/normalize.css";

/**
 * The index html will be generated from this file. You can customize things as
 * you see fit. `body` and `head` will be generated by the server and you
 * should not remove those or the application will likely stop working.
 */
export default class Index extends Component {
  render () {
    const {
      head,
      body
    } = this.props;
    return (
      <html lang="en-us">
        <head>
          <title>Welcome</title>
          {head /* DO NOT REMOVE */}
        </head>
        <body>
          {body /* DO NOT REMOVE */}
        </body>
      </html>
    );
  }
}

