export const validProjectPackage = {
  name: 'AppName',
  version: '1.0.0',
  description: '',
  main: 'index.js',
  scripts: {
    start: 'gluestick start',
    test: 'echo "Error: no test specified" && exit 1',
  },
  dependencies: {
    'app-module-path': '2.2.0',
    axios: '0.12.0',
    'babel-cli': '6.22.2',
    'babel-core': '6.22.1',
    'babel-eslint': '7.1.1',
    'babel-plugin-closure-elimination': '1.1.14',
    'babel-plugin-react-transform': '2.0.2',
    'babel-plugin-transform-decorators-legacy': '1.3.4',
    'babel-plugin-transform-react-constant-elements': '6.22.0',
    'babel-plugin-transform-react-inline-elements': '6.22.0',
    'babel-polyfill': '6.22.0',
    'babel-preset-es2015': '6.22.0',
    'babel-preset-react': '6.22.0',
    'babel-preset-stage-0': '6.22.0',
    'babel-register': '6.22.0',
    'babel-traverse': '^6.22.1',
    chalk: '1.1.3',
    chokidar: '1.6.1',
    commander: '2.9.0',
    compression: '1.6.2',
    'cross-spawn': '5.0.1',
    cssnano: '3.10.0',
    deepmerge: '1.3.1',
    'electrode-react-ssr-caching': '0.1.5',
    enzyme: '2.7.1',
    eslint: '^3.13.0',
    'eslint-config-airbnb': '14.0.0',
    'eslint-plugin-import': '2.2.0',
    'eslint-plugin-jsx-a11y': '3.0.2',
    'eslint-plugin-react': '^6.9.0',
    'eventsource-polyfill': '0.9.6',
    express: '4.14.0',
    'express-pino-logger': '2.0.0',
    'extract-text-webpack-plugin': '2.0.0-beta.5',
    'fs-extra': '2.0.0',
    'gluestick-shared': '0.4.22',
    handlebars: '4.0.6',
    'http-proxy-middleware': '0.17.3',
    inquirer: '3.0.1',
    jest: '18.1.0',
    'lru-cache': '4.0.2',
    'match-media': '0.2.0',
    mkdirp: '0.5.1',
    'optimize-css-assets-webpack-plugin': '1.3.0',
    'oy-vey': '0.8.0',
    pino: '3.2.0',
    pm2: '2.3.0',
    radium: '0.18.1',
    react: '15.4.2',
    'react-addons-test-utils': '15.4.2',
    'react-dom': '15.4.2',
    'react-hot-loader': '1.3.1',
    'react-loader': '2.4.0',
    'react-redux': '5.0.2',
    'react-router': '3.0.2',
    'react-transform-catch-errors': '1.0.2',
    'react-transform-hmr': '1.0.4',
    'redbox-react': '1.3.3',
    redux: '3.6.0',
    'replace-in-file': '2.2.2',
    'require-hacker': '2.1.4',
    rimraf: '2.5.4',
    semver: '5.3.0',
    'serialize-javascript': '1.3.0',
    sha1: '1.1.1',
    shelljs: '0.7.6',
    'sorted-object': '2.0.1',
    'stream-to-string': '1.1.0',
    temp: '0.8.3',
    'url-loader': '0.5.7',
    webpack: '2.2.0',
    'webpack-dev-middleware': '1.9.0',
    'webpack-hot-middleware': '2.15.0',
    'webpack-isomorphic-tools': '2.5.8',
    'webpack-merge': '2.4.0',
  },
  author: '',
  license: 'ISC',
  devDependencies: {
    axios: '0.12.0',
    'babel-eslint': '7.1.1',
    'electrode-react-ssr-caching': '0.1.5',
    enzyme: '2.7.1',
    eslint: '3.14.1',
    'eslint-config-airbnb': '^14.0.0',
    'eslint-plugin-import': '^2.2.0',
    'eslint-plugin-jsx-a11y': '^3.0.2',
    'eslint-plugin-react': '6.9.0',
    'flow-bin': '^0.38.0',
    'gluestick-shared': '0.4.22',
    jest: '18.1.0',
    'oy-vey': '0.8.0',
    radium: '0.18.1',
    react: '15.4.2',
    'react-addons-test-utils': '15.4.2',
    'react-dom': '15.4.2',
    'react-redux': '5.0.2',
    'react-router': '3.0.2',
    redux: '3.6.0',
    'stream-to-string': '1.1.0',
    temp: '0.8.3',
  },
};

export const validLargerProjectPackage = {
  ...validProjectPackage,
  dependencies: {
    ...validProjectPackage.dependencies,
    axios: '9.9.9',
  },
};

export const invalidProjectPackage = {
  ...validProjectPackage,
  dependencies: {
    ...validProjectPackage.dependencies,
    axios: '0.0.1',
  },
};

const missingProjectPackage = {
  ...validProjectPackage,
  dependencies: {
    ...validProjectPackage.dependencies,
  },
};
delete missingProjectPackage.dependencies.axios;
export { missingProjectPackage };
